function f = cross2mat(w)
%CROSS2MAT
%    F = CROSS2MAT(W1,W2,W3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2021 12:32:28
w1 = w(1);
w2 = w(2);
w3 = w(3);
f = reshape([0.0,w3,-w2,-w3,0.0,w1,w2,-w1,0.0],[3,3]);
