function abs_der = ode_fun(t)
%ODE_FUN
%    ABS_DER = ODE_FUN(T)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    29-Jan-2021 11:47:54

t2 = cos(t);
t4 = t.*2.0;
t5 = sin(t4);
t6 = t5.*3.0e2;
t3 = t2.*1.0e2+t6;
t7 = t6-sin(t).*1.0e2;
abs_der = sqrt(t2.^2+t3.^2./2.5e1+t7.^2./2.5e1).*5.0;
